# Generated by Django 4.2.5 on 2023-09-07 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_motorista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField(verbose_name='Data_saida')),
                ('hora_saida', models.TimeField(verbose_name='Hora_saida')),
                ('km_saida', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Km_saida')),
                ('destino', models.CharField(max_length=100, verbose_name='Destino')),
                ('data_retorno', models.DateField(verbose_name='Data_retorno')),
                ('hora_retorno', models.TimeField(verbose_name='Hora_retorno')),
                ('km_retorno', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Km_retorno')),
                ('km_percorrido', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Km_percorrido')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veiculo')),
            ],
        ),
    ]
