# Generated by Django 4.2.5 on 2023-09-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aluguel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='cnh',
            field=models.IntegerField(verbose_name='CNH'),
        ),
    ]
